### ISSUE TITLE
[ENHANCEMENT] Node Health Metrics with Detailed Per-Chain Gauges

### ISSUE THREAD

**Issue by Maxitosh** [pokt-network/gateway-server#43]
## Description

Having detailed metrics about node healthiness per chain can significantly enhance monitoring and troubleshooting capabilities. The following metrics will provide valuable insights:

- **Number of Healthy Nodes per Chain**: Tracks deemed healthy nodes based on Gateway QoS checks.
- **Number of Synced Nodes per Chain**: Indicates nodes that are fully synced with the blockchain.
- **Number of Nodes in Timeout per Chain**: Monitors the number of nodes that are currently in a timeout state (banned).

## Expected Behavior

These metrics should be exported in Prometheus format and available for scraping at the `/metrics` endpoint. This will enable seamless integration with existing monitoring systems and dashboards, allowing for real-time tracking and alerting on the health and status of nodes across different chains.

**Comment by nodiesBlade** [comment]
Thanks for your contribution, this will be included in next minor release.
